### ISSUE TITLE
Module does not exist while creating components for modules with snake-case

### ISSUE THREAD

**Issue by jagged3dge** [mcfly-io/generator-mcfly#245] opened 2015-09-08 10:14 UTC
I am using snake-case names for my project. I have created a module with the name `uiAutofill` to contain a directive called `autoFill`. So, the module folder is named `ui-autofill`. However, when I try to generate the directive, it keeps saying `Error: The module name 'ui-autofill' does not exist.`

This happens even when I'm not providing a module name upfront while initiating the directive sub-generator.

Steps to reproduce:
1. Create a module: `yo mcfly:module uiAutofill`
2. Try to create a directive with either of these commands:
* `yo mcfly:directive uiAutofill autoFill --compile=false` or
* `yo mcfly:directive --compile=false` then choose `ui-autofill` when prompted to select module

I'm using the latest generator version 1.7.4.

Here's the auto-generated `yo-rc.json` file for my project:
```json
{
  "generator-mcfly": {
    "filenameCase": "snake",
    "filenameSuffix": true,
    "appname": "ngMcflyLazyTest",
    "clientFolder": "client",
    "ionic": false,
    "famous": false,
    "ngCordova": false,
    "fontawesome": false,
    "bootstrap": false,
    "material": false
  }
}
```

**Comment by jskrzypek** [comment] 2015-09-08 10:17
I'll check this out in a little bit...

**Comment by jagged3dge** [comment] 2015-09-08 10:20
Thanks for the quick reply :)

Here's a screenshot of the commands I've used:
![mcfly-modulenotfounderror](https://cloud.githubusercontent.com/assets/3892333/9732401/3dc11d42-5641-11e5-9951-2b5c807f2dd8.JPG)

**Comment by jskrzypek** [comment] 2015-09-08 12:59
@jagged3dge, I can reproduce the issue and I'm diagnosing it now.

My first guess is the problem comes from the way the generator figures out which modules exist.

**Comment by jskrzypek** [comment] 2015-09-08 15:01
Yup that was it. I'm fixing it now.

**Comment by jskrzypek** [comment] 2015-09-08 15:14
It looks like the problem was coming from the fact that the app was checking the existing module folder names that get stuck in `this.clientModules` (and are casified according to the preferences in `.yo-rc.json`) for the requested `this.modulename` (which is always camelized, since this is the name used for angular).

An example is here: https://github.com/mcfly-io/generator-mcfly/blob/master/class/component.js#L123

I've changed the places where this check occurs to check `this.clientModules` for `this.moduleFolder`, which is the correctly casified folder name.

**Comment by jagged3dge** [comment] 2015-09-08 17:27
Thanks for the fix! ^_^ Should I wait for the next release or install from the master branch?

**Comment by jskrzypek** [comment] 2015-09-08 17:35
We're still reviewing/testing the PR to make sure it doesn't break anything, so I haven't merged the master yet. I'd expect it tomorrow or Thursday.

If you want it sooner, I'd just monkey-patch the version installed in your global `node_modules` folder. I think this is in your `%AppData%\npm\node_modules` folder on windows. 

Implement the patch based on this commit: https://github.com/mcfly-io/generator-mcfly/commit/9181611d71fd25bd6e1e2e2e2aa8a55ba9efde8d

**Comment by jagged3dge** [comment] 2015-09-08 17:44
Monkey-patching for the win! Works smoothly. Thanks again :+1:

**Comment by jskrzypek** [comment] 2015-09-08 17:52
:+1:

**Closed** 2015-09-09 07:31 UTC
