### ISSUE TITLE
how to install the dependencies?gulp not work.

### ISSUE THREAD

**Issue by axetroy** [mcfly-io/generator-mcfly#313] opened 2016-03-16 18:00 UTC
even I run command
```bash
./bin/prepublish.sh
```
and the dependencies has been install in global env

but when I run gulpd.

it will report some error like
```bash
[axetroy@axetroy-pc mcfly-ionic]$ gulp browsersync
module.js:341
    throw err;
    ^

Error: Cannot find module 'gulp-help'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/axetroy/developer/angular/mcfly-ionic/gulpfile.js:4:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

and then ,ok~~!i will install it by hand.

and then it will require other module some one can't install.

so,the question is:

how to install all the dependencies?

somebody can tell?

**Comment by thaiat** [comment] 2016-03-16 18:26
npm install

**Comment by axetroy** [comment] 2016-03-17 06:05
@thaiat 
not work~!
the dependencies not write in ``package.json`` but in ``prepublish.sh``

[``npm install``] mean nothing install

**Comment by thaiat** [comment] 2016-03-17 07:38
sorry but you ll have to be more explicit about what you are doing

this is standard nodejs, npm install cannot "not work"....

**Comment by prestonvanloon** [comment] 2016-03-21 18:17
A lot of the dependencies are not in the package.json. `npm install` does not install those missing dependencies

**Comment by prestonvanloon** [comment] 2016-03-21 18:17
Might be a duplicate of #306

**Comment by thaiat** [comment] 2016-03-21 18:19
i have just updated the package, can you with the latest version ?

**Comment by prestonvanloon** [comment] 2016-03-21 18:21
To replicate this error:

- Create a new app with mcfly
- `rm -rf node_modules`
- `npm install && ./bin/prepackage.sh`

I will try updating to the latest version

**Comment by prestonvanloon** [comment] 2016-03-21 18:34
v2.0.5 seems to work just fine. Thanks!

**Comment by thaiat** [comment] 2016-03-21 18:42
cool, closing this issue for now, feel free to reopen

**Closed by thaiat** 2016-03-21 18:42 UTC
